<a href="https://colab.research.google.com/github/icarocamelo/inf-6333-applied-ai/blob/main/linear-regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/icarocamelo/inf-6333-applied-ai/main/dataset/node1.csv', header=None)
data.columns = ['Time', 'Busy System', 'Busy User', 'Busy Iowait', 'Busy IRQs', 'Busy Other', 'Idle']
print('Number of instances = %d' % (data.shape[0]))
print('Number of attributes = %d' % (data.shape[1]))
data.head()

Number of instances = 671
Number of attributes = 7

,Time,Busy System,Busy User,Busy Iowait,Busy IRQs,Busy Other,Idle
0,2022-03-04 16:12,24.0,375.0,1.980,13.4,0.0955,492.0
1,2022-03-04 16:16,31.3,1148.0,0.733,23.4,0.1330,30.5
2,2022-03-04 16:20,41.5,762.0,3.720,25.0,0.1370,599.0
3,2022-03-04 16:24,34.6,952.0,1.770,20.9,0.1410,323.0
4,2022-03-04 16:28,44.6,67.3,4.680,17.8,1.2300,1452.0